// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQXLQY2H7Fp3xI1AvcpVpjGtljKVm5g80',
    appId: '1:89587621564:web:30e8ed1d53913437e2bab9',
    messagingSenderId: '89587621564',
    projectId: 'simple-recipe-pl',
    authDomain: 'simple-recipe-pl.firebaseapp.com',
    storageBucket: 'simple-recipe-pl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgqEtsBtrEWH0Nf0eiTQhys96NANJ-nI',
    appId: '1:89587621564:android:540c34630f883221e2bab9',
    messagingSenderId: '89587621564',
    projectId: 'simple-recipe-pl',
    storageBucket: 'simple-recipe-pl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxwfhJ6D-Kbu1VkL2bZkGRaQXt8pw9zWE',
    appId: '1:89587621564:ios:5822c1cbaeea7e1be2bab9',
    messagingSenderId: '89587621564',
    projectId: 'simple-recipe-pl',
    storageBucket: 'simple-recipe-pl.appspot.com',
    iosClientId: '89587621564-ctfuj36b2vngqrb4dghktubnn9jg47sb.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcpNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxwfhJ6D-Kbu1VkL2bZkGRaQXt8pw9zWE',
    appId: '1:89587621564:ios:a38263eec3b22769e2bab9',
    messagingSenderId: '89587621564',
    projectId: 'simple-recipe-pl',
    storageBucket: 'simple-recipe-pl.appspot.com',
    iosClientId: '89587621564-e8u3i70j5kpjnab2jgmojh27mc76ferp.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcpNew.RunnerTests',
  );
}
